version: "3"
services:
  bot:
    build: .
    volumes:
      - .:/usr/app/ # for dev only
      - /usr/app/node_modules
    depends_on:
      - graphite
  graphite:
    image: graphiteapp/graphite-statsd:latest
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
