version: "3"
services:
  bot:
    build: .
    volumes:
      - .:/usr/app/ # for dev only
      - /usr/app/node_modules
    depends_on:
      - graphite
  graphite:
    image: graphiteapp/graphite-statsd:latest
